### ISSUE TITLE
React fungerar inte? What?

### ISSUE THREAD

**Issue by jesperorb** [FEND16/javascript3#2]
**Innan du frågar, har du sett över följande:**
- [x] Kollat efter error i `Console` i din browser?
- [x] Kollat efter error i terminalen/kommandotolken?
- [x] Står i rätt mapp och har sparat alla filer du jobbar på?
- [x] Laddat om sidan (samt gjort en [__hard refresh__](https://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome) på sidan)?

### Förväntat beteende

Det funkar inte, lol

### Faktiskt beteende

Det ska fungera??

### Error / kod

_Exempel_
```
./src/App.js
  Line 9:  'Header' is not defined  react/jsx-no-undef

Search for the keywords to learn more about each error.
```

### Övrig information

* __Operativsystem:__ _macOS Sierra 10.12.6 / Windows 10 / Ubuntu 16.04_
* __Browser:__ _Chrome 60 / Firefox 54 / Safari 10.1.12_
* Övrig information om din dator som kan vara nödvändig

**Comment by jesperorb** [comment]
@EddieJostell Kan du lösa detta? SNälla? 100 kr, siwsh 070 98 28 56

**Comment by HumanDecoy** [comment]
![image](https://user-images.githubusercontent.com/21176110/29609438-808975cc-87f7-11e7-8150-c4156306e57d.png)
