### ISSUE TITLE
problem med create-react-app

### ISSUE THREAD

**Issue by 4886Talga** [FEND16/javascript3#4]
**Har fått problem med  ett nytt create-react-app projekt**
Försökte starta ett nytt projekt med create-react-app. Gjorde som vanligt  

```
create-react-app new-project
```
och har fått ett fel vid körningen.

npm ERR! path C:\Users\4886t\Desktop\brevery-db\node_modules\nan\package.json
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\4886t\Desktop\brevery-db\node_modules\nan\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\4886t\Desktop\brevery-db\node_modules\nan\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\4886t\\Desktop\\brevery-db\\node_modules\\nan\\package.json\'\n    at Error (n     ative)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\4886t\\Desktop\\brevery-db\\node_modules\\nan\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\4886t\AppData\Roaming\npm-cache\_logs\2017-09-04T13_42_20_011Z-debug.log

Aborting installation.
  npm install --save --save-exact --loglevel error react react-dom react-scripts has failed.

### Försökte med att stänga av antivirus programet och köra

```
npm cache clean --force

```
men får igen samma fel. Är det någon som har upplevt samma?

*  Operativsystem: Windows 10 
*  Browser: Chrome 60

**Comment by jesperorb** [comment]
@4886Talga kör sällan Windows 10 så vet inte vilket problemet kan vara men det ser ut att vara någonting med felaktika rättigheter, du kan alltid testa:
- [x] Köra terminalen/kommandotolken som Admin
- [x] Stänga ner alla program som använder filerna/mappen och testa köra `create-react-app` igen

**Comment by 4886Talga** [comment]
Körde som du sa men samma fel.

**Comment by jesperorb** [comment]
@4886Talga utöver det, det enda jag kan tänka mig:
- [x] Starta om datorn
- [x] Öppna en ny terminal 
- [x] Testa att uppdatera `node` och `npm`
- [x] Testa en annan terminal eller testa _yarn_ istället

**Comment by 4886Talga** [comment]
Uppgraderade node till senaste version men körde tillbaka npm till v5.3 och allt funkar som det ska.
